### PR TITLE
Use of BT and various fixes (including renders of documentation)

### PR DESCRIPTION
**Pull request by khufkens**
HI @imfeldn, here are fixes to implement the Bayesiantools approach.

When using DEzs instead of generic MCMC no chains need to be specified. The algorithm deals with starting conditions it seems (see BT docs).

I only changed one of the runs.

### CODE REVIEW

**Comment by khufkens** [comment]
You will need to update phenor, given the previous `pr_fit_comparison()` issue

**Comment by imfeldn** [comment]
Thanks for the adjustments! I started testing the code, there seems to be an issue in the update of phenor:
 
On line 198 in pr_fit_comparison, it is:

if(inherits("try-error", par)) {return(NULL)}

but maybe it should be turned?

if(inherits(par,"try-error")) {return(NULL)}

I created a new function that I can use instead, so there's no hurry to update it.

**Comment by khufkens** [comment]
Ok, that explains some of the weirdness I've been seeing when parameters are out of range. Thanks for debugging @imfeldn. If you can, instead do a pull request. Thing is that with personal functions the issue doesn't get resolved for others. Most developers, including myself, welcome contributions like this as we all do this on our free time and don't have enough eyes and hands to fix a lot of this.

**Comment by khufkens** [comment]
I'll take this one though. I'll let you know when you can reinstall phenor

**Comment by khufkens** [comment]
Should be fixed!

**Comment by imfeldn** [comment]
Perfect, thanks!
________________________________
Von: Koen Hufkens ***@***.***>
Gesendet: Montag, 28. August 2023 14:54
An: imfeldn/swiss_pheno ***@***.***>
Cc: Imfeld, Noemi (GIUB) ***@***.***>; Mention ***@***.***>
Betreff: Re: [imfeldn/swiss_pheno] Use of BT and various fixes (including renders of documentation) (PR #5)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Should be fixed!

**Pull request merged**
