### PR TITLE
refactoring code + data shuffle + moving to RDS

### PR DESCRIPTION
**Pull request by khufkens**
Hi @imfeldn,

These are a lot of changes, if you feel uncomfortable pulling this in at once, don't. Basically I couldn't test the new RDS conversion routines. It is just saving it in a different format and should be ok, but better measure twice and cut once.

I suggest to download (git clone) my repository first (so the one under khufkens), then formally test the code (especially the generation of the new RDS files) in a temporary location on your machine (you can quit after one file, doesn't need to be the whole routine obviously). If this all works, then pull this in!

### CODE REVIEW

**Comment by khufkens** [comment]
Could you hold off merging this, need to figure some things out first!!

**Comment by khufkens** [comment]
Thanks, will sync my fork if you push new changes. Thanks also for collaborating on github so smoothly!

**Comment by imfeldn** [comment]
Hi,

I pushed some changes. Now it should run based on the original data. I also added the "class feature" in the data selection/naming. I hope that's okay. It allows to easily add more of the pheno stations with lower quality rating.

Now the other scripts need updating too, since they still rely on the .RData objects. I can make these adjustments there, and also, e.g. move the ploting out of the scripts. But maybe it makes sense to discuss, where we're heading with respect to the calibration?

Cheers,

Noemi
________________________________
Von: Koen Hufkens ***@***.***>
Gesendet: Dienstag, 15. August 2023 18:57
An: imfeldn/swiss_pheno ***@***.***>
Cc: Imfeld, Noemi (GIUB) ***@***.***>; State change ***@***.***>
Betreff: Re: [imfeldn/swiss_pheno] refactoring code + data shuffle + moving to RDS (PR #2)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Thanks, will sync my fork if you push new changes. Thanks also for collaborating on github so smoothly!

**Comment by khufkens** [comment]
Yes, I didn't know what the class feature was so I left as is. Good point including this if this is an important (flexible) variable. Anything that makes code more generalizable.

For consistency you can change everything from RData, but I didn't want to insist on this as this is mostly data preparation and this is basically out of reach of anyone who wants to reproduce the results (it is "given").

We should have a look at where we go with calibration. I'll open a separate discussion (issue) for this, and it might be good to sit down on a Tuesday. With the workflows in place it should be easier to juggle some of these things and coordinate better.

**Comment by imfeldn** [comment]
I'll update the other scripts then as well. Should we meet next Tuesday, 22 August to discuss the open issue?
________________________________
Von: Koen Hufkens ***@***.***>
Gesendet: Mittwoch, 16. August 2023 11:42
An: imfeldn/swiss_pheno ***@***.***>
Cc: Imfeld, Noemi (GIUB) ***@***.***>; State change ***@***.***>
Betreff: Re: [imfeldn/swiss_pheno] refactoring code + data shuffle + moving to RDS (PR #2)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Yes, I didn't know what the class feature was so I left as is. Good point including this if this is an important (flexible) variable. Anything that makes code more generalizable.

For consistency you can change everything from RData, but I didn't want to insist on this as this is mostly data preparation and this is basically out of reach of anyone who wants to reproduce the results (it is "given").

We should have a look at where we go with calibration. I'll open a separate discussion (issue) for this, and it might be good to sit down on a Tuesday. With the workflows in place it should be easier to juggle some of these things and coordinate better.

**Comment by khufkens** [comment]
Sure, does 15:30 work like before? I've opened a new issue #3 so if you have any ideas / remarks you can put it down there.

**Comment by imfeldn** [comment]
Perfect, Tuesday, 15.30 is fine!

**Pull request merged**
